Add new config option allowVisibleSource
hackmdio/codimd pull request #1599
Opened 2020-09-18 12:11 UTC by roman-yatsenko

Add new config option allowVisibleSource to the project. The default value for this option is true. The false value will block Edit and Both editor modes for users that have no rights to edit a note. 

Pull request adds:

- new config option allowVisibleSource with default value true;
- new environment variable CMD_VISIBLE_SOURCE;
- disable Edit and Both modes for users without edit note permission;
- redirect form Edit and Both modes to View mode by direct URL with mode parameter.

2020-10-23 02:26 UTC, a60814billy commented on public/js/index.js
> +function disableControls () {
Using more precise function name here.
Maybe can change `disableControls`to `disableModeChangeControls` and 
 `enableControls` to `enableModeChangeControls`

2020-10-23 02:26 UTC, a60814billy commented on public/js/index.js
> +function checkParametr (isLogin, permission) {
```suggestion
function checkParameter (isLogin, permission) {
```

2020-10-23 02:26 UTC, a60814billy commented on public/js/index.js
> +function replaceUrl (url) {
`replaceUrl` -> `replaceUrlToViewMode`

2020-10-23 02:26 UTC, a60814billy commented on public/js/index.js
> +  if (Object.prototype.hasOwnProperty.call(userPersonalInfo, 'login')) {
```js
function userIsLogin (userPersonalInfo) {
  return !!userPersonalInfo && !!userPersonalInfo.login
}
```

2020-10-23 02:26 UTC, a60814billy commented on public/js/index.js
>  ui.toolbar.mode.click(function () {
introduce a function `isAllowUserChangeMode`
```js
function isAllowUserChangeMode () {
  const isOwner = personalInfo.userid && window.owner && personalInfo.userid === window.owner
  return isOwner || !blockSourceView
}
```

and mode select logic would be

```js
if (isAllowUserChangeMode()) {
    return toggleMode()
}
```

2020-10-23 02:29 UTC, a60814billy requested changes
Hi @roman-yatsenko, thanks for your contribution, It's a good feature.
But we need some refactoring to meet project coding conventions before merge.

2020-10-23 02:30 UTC, a60814billy commented
By the way, please sign DCO

2020-10-26 13:44 UTC, roman-yatsenko commented on lib/config/default.js
> +  allowVisibleSource: true,
With the default value `true` user can see note source (edit and both modes are enabled for view to user without edit rights). The true value is an usual CodiMD behavior for now.
P.S. But we've refactored as you wish :-)

2020-10-26 13:50 UTC, roman-yatsenko commented
> By the way, please sign DCO

We have a git problems with DCO commit signs (Can't sign done commits). Can we accept the pull request without DCO? Or we can create a new pull request with one signed commit with all code. 
What we need to do?

2020-10-30 07:53 UTC, a60814billy commented
Hi, @roman-yatsenko 
Due to AGPL licesne, we can't accept any code without DCO sign. Please open a new pull request to do it!

2020-11-16 21:21 UTC, JamesHow1ett approved these changes

2020-11-17 09:52 UTC, closed without merging

2020-11-17 09:53 UTC, roman-yatsenko commented
Recreated at https://github.com/hackmdio/codimd/pull/1621